// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHomeGroup_VillaApi.Data;

namespace MyHomeGroup_VillaApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221020095612_villasamenties")]
    partial class villasamenties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyHomeGroup_VillaApi.Models.Amenties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AmphiTheater")
                        .HasColumnType("bit");

                    b.Property<bool>("BasketballCourt")
                        .HasColumnType("bit");

                    b.Property<bool>("ChildrensPlayArea")
                        .HasColumnType("bit");

                    b.Property<bool>("ClubHouseWithWater")
                        .HasColumnType("bit");

                    b.Property<bool>("CricketNets")
                        .HasColumnType("bit");

                    b.Property<bool>("DogsPark")
                        .HasColumnType("bit");

                    b.Property<bool>("Duplex")
                        .HasColumnType("bit");

                    b.Property<bool>("FitnessStation")
                        .HasColumnType("bit");

                    b.Property<bool>("JaggingCycleTrack")
                        .HasColumnType("bit");

                    b.Property<bool>("PartyLawn")
                        .HasColumnType("bit");

                    b.Property<bool>("SkatingRank")
                        .HasColumnType("bit");

                    b.Property<bool>("SwimmingPool")
                        .HasColumnType("bit");

                    b.Property<bool>("TennisCourt")
                        .HasColumnType("bit");

                    b.Property<bool>("Triplex")
                        .HasColumnType("bit");

                    b.Property<bool>("YogaMeditationLawn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Amenties");
                });

            modelBuilder.Entity("MyHomeGroup_VillaApi.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AmentiesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("PriceRangeStarts")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AmentiesId");

                    b.ToTable("Villas");
                });

            modelBuilder.Entity("MyHomeGroup_VillaApi.Models.Villa", b =>
                {
                    b.HasOne("MyHomeGroup_VillaApi.Models.Amenties", "Amenties")
                        .WithMany()
                        .HasForeignKey("AmentiesId");

                    b.Navigation("Amenties");
                });
#pragma warning restore 612, 618
        }
    }
}
